# Generated by Django 5.0.4 on 2024-08-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacoes',
            options={'managed': False, 'verbose_name': 'Investiment', 'verbose_name_plural': 'Investiments'},
        ),
        migrations.AlterModelOptions(
            name='cargosesalarios',
            options={'managed': False, 'verbose_name': 'Position and Salary', 'verbose_name_plural': 'Positions and Salaries'},
        ),
    ]
