# Generated by Django 5.0.4 on 2024-08-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_aplicacoes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesasadministrativas',
            options={'managed': False, 'verbose_name': 'Despesa Administrativa', 'verbose_name_plural': 'Despesas Administrativas'},
        ),
    ]
