# Generated by Django 5.0.4 on 2024-09-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_despesasadministrativas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargosesalarios',
            options={'managed': False, 'verbose_name_plural': 'Cargos e Salarios'},
        ),
        migrations.AlterModelOptions(
            name='controle',
            options={'managed': False, 'verbose_name_plural': 'Controle de Cooperados'},
        ),
        migrations.AlterModelOptions(
            name='execucaoorcamentaria',
            options={'managed': False, 'verbose_name': 'Execucao Orcamentaria', 'verbose_name_plural': 'Execucoes Orcamentarias'},
        ),
        migrations.AlterModelOptions(
            name='fluxosdecaixa',
            options={'managed': False, 'verbose_name': 'Fluxo de Caixa', 'verbose_name_plural': 'Fluxos de Caixas'},
        ),
        migrations.AlterModelOptions(
            name='historicodereajustes',
            options={'managed': False, 'verbose_name': 'Historico de Reajuste', 'verbose_name_plural': 'Historico de Reajustes'},
        ),
        migrations.AlterModelOptions(
            name='historicoindicesfinanceiros',
            options={'managed': False, 'verbose_name': 'Historico de Indices Financeiros', 'verbose_name_plural': 'Historico de Indices Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='historicomatriculas',
            options={'managed': False, 'verbose_name': 'Historico de Matriculas', 'verbose_name_plural': 'Historico de Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='historicoorcamentario',
            options={'managed': False, 'verbose_name': 'Historico Orcamentario', 'verbose_name_plural': 'Historico Orcamentario'},
        ),
        migrations.AlterModelOptions(
            name='ifes',
            options={'managed': False, 'verbose_name_plural': 'IFES'},
        ),
        migrations.AlterModelOptions(
            name='matriculas',
            options={'managed': False, 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='ofertas',
            options={'managed': False, 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='parametros',
            options={'managed': False, 'verbose_name_plural': 'Parametros'},
        ),
        migrations.AlterModelOptions(
            name='previsaoorcamentaria',
            options={'managed': False, 'verbose_name_plural': 'Previsao Orcamentaria'},
        ),
        migrations.AlterModelOptions(
            name='projecaofates',
            options={'managed': False, 'verbose_name_plural': 'Projecao Fates'},
        ),
    ]
