# Generated by Django 5.0.4 on 2024-09-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_cargosesalarios_options_alter_controle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecaofates',
            options={'managed': False, 'verbose_name_plural': 'Projecao_Fates'},
        ),
    ]
