# Generated by Django 5.0.4 on 2024-09-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_projecaofates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomatriculas',
            options={'managed': True, 'verbose_name': 'Historico de Matriculas', 'verbose_name_plural': 'Historico de Matriculas'},
        ),
    ]
