# Generated by Django 5.0.4 on 2024-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_historicomatriculas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoindicesfinanceiros',
            options={'managed': True, 'verbose_name': 'Historico de Indices Financeiros', 'verbose_name_plural': 'Historico de Indices Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='historicomatriculas',
            options={'managed': False, 'verbose_name': 'Historico de Matriculas', 'verbose_name_plural': 'Historico de Matriculas'},
        ),
    ]
