# Generated by Django 5.0.4 on 2024-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_historicoindicesfinanceiros_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='cem',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='cinco',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='cinco_relativo',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='ciquenta',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='dez',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='dez_relativo',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='dois',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='metade',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='negativo_relativo',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='quatro',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='quinze',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='tres',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='tres_quarto',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='trinta_relativo',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='um',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='um_quarto',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='zero',
        ),
        migrations.RemoveField(
            model_name='historicoindicesfinanceiros',
            name='zero_relativo',
        ),
        migrations.AddField(
            model_name='historicoindicesfinanceiros',
            name='sobra_bruta',
            field=models.FloatField(blank=True, db_column='Sobra Bruta', null=True),
        ),
        migrations.AlterField(
            model_name='historicoindicesfinanceiros',
            name='data',
            field=models.DateTimeField(blank=True, db_column='Data', null=True),
        ),
    ]
