# Generated by Django 5.0.4 on 2024-09-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_historicoindicesfinanceiros_cem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoindicesfinanceiros',
            options={'managed': False, 'verbose_name': 'Historico de Indices Financeiros', 'verbose_name_plural': 'Historico de Indices Financeiros'},
        ),
    ]
