# Generated by Django 5.0.4 on 2024-12-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_historicoindicesfinanceiros_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, db_column='Data', null=True)),
                ('numero_cooperado', models.FloatField(blank=True, db_column='Numero Cooperado', null=True)),
                ('cooperado', models.TextField(blank=True, db_column='Cooperado', null=True)),
                ('data_indicacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Indicacoes',
                'db_table': 'Indicacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cooperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndicacaoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_indicacao', models.DateField()),
                ('cooperado_indicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cooperado')),
                ('indicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.indicacao')),
            ],
        ),
    ]
