# Generated by Django 5.0.4 on 2024-12-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_indicacao_cooperado_indicacaodetalhe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacao',
            options={'verbose_name_plural': 'Indicacoes'},
        ),
        migrations.AlterModelOptions(
            name='indicacaodetalhe',
            options={'verbose_name_plural': 'Detalhes Indicacoes'},
        ),
        migrations.AlterModelTable(
            name='indicacaodetalhe',
            table='Detalhe Indicacao',
        ),
    ]
