# Generated by Django 5.0.4 on 2024-12-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_indicacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='indicados',
            field=models.ManyToManyField(related_name='indicados_por', through='main_app.IndicacaoDetalhe', to='main_app.cooperado'),
        ),
    ]
