# Generated by Django 5.0.4 on 2024-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_indicacao_indicados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='indicados',
        ),
        migrations.RemoveField(
            model_name='indicacaodetalhe',
            name='cooperado_indicado',
        ),
        migrations.RemoveField(
            model_name='indicacaodetalhe',
            name='indicacao',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='data_indicacao',
        ),
        migrations.AddField(
            model_name='indicacao',
            name='cooperado_indicado',
            field=models.TextField(blank=True, db_column='Cooperado Indicado', null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='numero_cooperado_indicado',
            field=models.FloatField(blank=True, db_column='Numero Cooperado Indicado', null=True),
        ),
        migrations.DeleteModel(
            name='Cooperado',
        ),
        migrations.DeleteModel(
            name='IndicacaoDetalhe',
        ),
    ]
