# Generated by Django 5.0.4 on 2024-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_indicacao_indicados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacao',
            name='numero_cooperado',
            field=models.IntegerField(blank=True, db_column='Numero Cooperado', null=True),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='numero_cooperado_indicado',
            field=models.IntegerField(blank=True, db_column='Numero Cooperado Indicado', null=True),
        ),
    ]
