# Generated by Django 5.0.4 on 2024-12-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_indicacao_numero_cooperado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controle',
            options={'verbose_name_plural': 'Controle de Cooperados'},
        ),
    ]
