# Generated by Django 5.0.4 on 2024-12-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_controle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='indicado',
        ),
        migrations.AlterField(
            model_name='controle',
            name='data',
            field=models.DateTimeField(blank=True, db_column='Data', null=True),
        ),
        migrations.AlterField(
            model_name='controle',
            name='numero_cooperado',
            field=models.IntegerField(blank=True, db_column='Numero Cooperado', null=True),
        ),
        migrations.AlterField(
            model_name='controle',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, db_column='Numero Parcelas', null=True),
        ),
    ]
