# Generated by Django 5.0.4 on 2024-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_controle_indicado_alter_controle_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaReceita',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, db_column='Data', null=True)),
                ('plano_de_contas', models.TextField(blank=True, db_column='Plano de Contas', null=True)),
                ('valor', models.FloatField(blank=True, db_column='Valor', null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('subtipo', models.TextField(blank=True, db_column='Subtipo', null=True)),
                ('categoria', models.TextField(blank=True, db_column='Categoria', null=True)),
            ],
            options={
                'verbose_name_plural': 'Despesas e Receitas',
                'db_table': 'Despesas e Receitas',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='controle',
            options={'managed': True, 'verbose_name_plural': 'Controle de Cooperados'},
        ),
        migrations.AlterModelOptions(
            name='indicacao',
            options={'managed': False, 'verbose_name_plural': 'Indicacoes'},
        ),
    ]
